remote_theme: jekyll/minima
title: Karla Melendez
description: Senior Technical Writer · Bilingual EN/ES · AI · Copyeditor · Translator
url: "https://karla-melendez.github.io"
author:
  name: Karla Melendez
  email: kemh.to@gmail.com

minima:
  nav_order:
    - index.md
    - about.md
    - services.md
    - portfolio.md
    - project.md
    - blog.md
    - contact.md

plugins:
  - jekyll-remote-theme
