theme: minima
title: Karla Melendez
description: Bilingual EN/ES · Conversational AI · Copyeditor · Translator
url: "https://karla-melendez.github.io"
author: Senior Technical Writer

# Navigation
header_pages:
  - index.md
  - about.md
  - services.md
  - portfolio.md
  - project.md
  - blog.md
  - contact.md
