theme: minima
title: Karla Melendez
description: Senior Technical Writer · Bilingual EN/ES · Conversational AI · Copyeditor · Translator
url: "https://karla-melendez.github.io"

# Navigation
header_pages:
  - about.md
  - services.md
  - portfolio.md
  - project.md
  - blog.md
  - contact.md
